name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: ["16", "18"]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Setup lerna
        run: yarn setup

      - name: Lint
        run: yarn lint

      - name: Check format
        run: yarn format

      - name: Run tests
        run: yarn test

      - name: Build
        run: yarn build

      - name: Build storybook
        run: yarn build-storybook
        working-directory: packages/react
